apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
  type: { { .Values.service.type } }
