name: CI/CD Pipeline

on:
  push:
    tag:
      - "*"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Only run on tag creation

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tienlong1106/git_cicd_api:${{ env.TAG_NAME }}
            tienlong1106/git_cicd_fe:latest

  update_config_repo:
    name: Update Config Repo with New Image Version
    runs-on: ubuntu-latest
    needs: push_to_registry # Ensure this job runs after push_to_registry

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v2
        with:
          repository: nguyentienlong1106/VDT_Config_web
          ref: "main"
          token: ${{ secrets.G_TOKEN }}

      - name: Update image tag in values.yaml
        run: |
          sed -i 's#tag:*#tag: ${{ env.TAG_NAME }}#g' values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "nguyentienlong1106"
          git config --global user.email "tienlong1106@gmail.com"
          git add values.yaml
          git commit -m "Update image tag to ${{ env.TAG_NAME }}"
          git push
